# Base image
FROM node:18-alpine AS base

# Install dependencies only when needed
FROM base AS deps
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the package-lock.json
COPY package.json package-lock.json ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Environment variables must be set during build time for Next.js if they are NEXT_PUBLIC_
# process.env.NEXT_API_URL and NEXT_AI_URL used in next.config.mjs are evaluated at runtime by Next.js server.
ARG NEXT_API_URL
ARG NEXT_AI_URL
ENV NEXT_API_URL=$NEXT_API_URL
ENV NEXT_AI_URL=$NEXT_AI_URL
ENV NEXT_TELEMETRY_DISABLED=1

RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

# Copy files
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json
COPY --from=builder /app/next.config.mjs ./next.config.mjs
COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/.next ./.next

EXPOSE 3000

ENV PORT=3000

# Start Next.js server
CMD ["npm", "run", "start"]
